In [12]:
import pandas as pd
import numpy as np

In [13]:
prices = pd.read_excel('data/CMO-Historical-Data-Monthly (2).xlsx', sheet_name='Monthly Prices', skiprows=4)

# Drop rows where 'Unnamed: 0' is NaN
prices = prices.dropna(subset=['Unnamed: 0'])

# Keep only rows where 'Unnamed: 0' contains '2022'
prices = prices[prices['Unnamed: 0'].str.contains('2022')]

prices_to_keep = [
    'Unnamed: 0',  # country name or ID

    # 🛢️ Energy
    'Crude oil, average',
    'Coal, Australian',
    'Natural gas, Europe',
    'Liquefied natural gas, Japan',

    # 🍫 Food and Beverage Crops
    'Cocoa',
    'Coffee, Arabica',
    'Tea, avg 3 auctions',

    # 🛢️ Vegetable Oils & Oilseeds
    'Coconut oil',
    'Groundnuts',
    'Groundnut oil **',
    'Palm oil',
    'Palm kernel oil',
    'Soybeans',
    'Soybean oil',
    'Soybean meal',
    'Rapeseed oil',
    'Sunflower oil',

    # 🌾 Grains
    'Barley',
    'Maize',
    'Sorghum',
    'Rice, Thai 5% ',  # keep 1 rice variety to avoid redundancy
    'Wheat, US SRW',   # soft red winter wheat (widely used)

    # 🍌 Fruits
    'Banana, Europe',
    'Orange',

    # 🥩 Animal Products
    'Beef **',
    'Chicken **',
    'Lamb **',
    'Shrimps, Mexican',

    # 🍬 Sugar and Tobacco
    'Sugar, world',
    'Tobacco, US import u.v.',

    # 🪵 Wood Products
    'Logs, Malaysian',
    'Sawnwood, Malaysian',
    'Plywood',

    # 🧵 Textiles & Rubber
    'Cotton, A Index',
    'Rubber, TSR20 **',

    # 🧪 Fertilizers
    'Phosphate rock',
    'DAP',
    'TSP',
    'Urea ',
    'Potassium chloride **',

    # 🏗️ Metals
    'Aluminum',
    'Iron ore, cfr spot',
    'Copper',
    'Lead',
    'Tin',
    'Nickel',
    'Zinc',
    'Gold',
    'Platinum',
    'Silver',
]

# Filter the DataFrame to keep only the specified columns
prices = prices[prices_to_keep]

# Rename the first column to 'month'
prices = prices.rename(columns={'Unnamed: 0': 'month'})

prices

,month,"Crude oil, average","Coal, Australian","Natural gas, Europe","Liquefied natural gas, Japan",Cocoa,"Coffee, Arabica","Tea, avg 3 auctions",Coconut oil,Groundnuts,...,Aluminum,"Iron ore, cfr spot",Copper,Lead,Tin,Nickel,Zinc,Gold,Platinum,Silver
745,2022M01,83.92,196.95,28.260673,14.68576,2.46736,5.976284,2.861902,2016.14,1479.55,...,3005.98,132.53,9782.34,2331.85,41791.7,22355.4,3599.14,1816.02,994.15,23.158
746,2022M02,93.543333,219.78,27.229716,16.995238,2.55094,6.169188,2.788359,2147.89,1496.25,...,3245.79,142.84,9943.17,2296.86,43983.35,24015.55,3620.04,1856.3,1049.4,23.542
747,2022M03,112.396667,314.04,42.392971,15.111385,2.45901,5.698502,2.613649,2230.22,1491.3,...,3498.37,152.07,10230.89,2344.84,43949.67,33924.18,3962.21,1947.83,1043.26,25.314
748,2022M04,103.413333,310.85,32.204187,16.287524,2.45535,5.854148,3.240668,2094.61,1443.75,...,3244.41,151.25,10161.38,2380.41,42991.11,33132.74,4360.43,1936.86,965,24.545
749,2022M05,110.096667,371.86,29.170723,16.679091,2.36662,5.741271,2.98525,1813.33,1482.95,...,2830.32,131.21,9377.15,2142.48,35769.39,28062.55,3751.48,1848.5,958.38,21.905
750,2022M06,116.8,374.08,33.557731,15.533921,2.32229,6.033824,2.964277,1700.5,1607.14,...,2563.44,130.74,9024.46,2066.38,31559.31,25658.63,3629.73,1836.57,956.59,21.556
751,2022M07,105.083333,402.2,51.33003,18.880754,2.23913,5.639197,3.308574,1540.53,1621.09,...,2408.42,108.57,7544.81,1985.2,25395.77,21481.89,3105.36,1732.74,869.25,19.075
752,2022M08,95.973333,406.97,70.04364,21.210848,2.32322,5.917861,3.369385,1384.57,1625,...,2430.79,108.85,7981.84,2072.72,24647.48,22057.39,3587.57,1764.56,908.65,19.724
753,2022M09,88.22,430.81,59.102622,23.733791,2.29846,5.897138,3.334399,1248.1,1641.67,...,2224.76,99.81,7746.01,1870.1,21124.04,22773.97,3124.97,1680.78,881.24,18.944
754,2022M10,90.326667,389.79,39.02205,21.841776,2.30902,5.292852,3.146871,1108.1,1619.05,...,2255.54,92.56,7651.08,1999.86,19391.17,22032.89,2967.21,1664.45,914.67,19.426
755,2022M11,87.376667,342.16,35.723282,19.586267,2.41204,4.715462,3.04666,1173.25,1639.29,...,2350.72,93.34,8049.86,2099.99,21249.5,25562.7,2938.92,1725.07,989.05,21.018
756,2022M12,78.066667,379.23,36.04426,20.576742,2.51231,4.629482,2.949394,1158.41,1670.45,...,2401.69,111.84,8375.4,2216.48,24172.37,28946.81,3129.48,1797.55,1010.95,23.326

In [ ]:
# Convert all columns except 'month' to numeric
prices.iloc[:, 1:] = prices.iloc[:, 1:].apply(pd.to_numeric, errors='coerce')

# Calculate monthly average percentage change
monthly_avg_pct_change = prices.iloc[:, 1:].pct_change().mean(axis=1)

# Find the index of the maximum average percentage increase
max_pct_increase_idx = monthly_avg_pct_change.idxmax()

# Extract the month and the average % increase
result = {
    'month': prices.loc[max_pct_increase_idx, 'month'],
    'average_percentage_increase': monthly_avg_pct_change[max_pct_increase_idx] * 100  # as percentage
}

result

/tmp/ipykernel_86263/149069822.py:5: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  monthly_avg_pct_change = prices.iloc[:, 1:].pct_change().mean(axis=1)
/tmp/ipykernel_86263/149069822.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  monthly_avg_pct_change = prices.iloc[:, 1:].pct_change().mean(axis=1)

{'month': '2022M03', 'average_percentage_increase': 9.548870461423665}

In [15]:
# code to calculate product name: percedntage increase from 2022M01 to 2022M03


# Calculate the percentage increase from 2022M01 to 2022M03 for each product
percentage_increase = (prices.iloc[2, 1:] - prices.iloc[0, 1:]) / prices.iloc[0, 1:] * 100
percentage_increase = percentage_increase.dropna()  # Drop NaN values
percentage_increase = percentage_increase.reset_index()
percentage_increase.columns = ['product', 'percentage_increase']
percentage_increase = percentage_increase.sort_values(by='percentage_increase', ascending=False)


hs6_codes = {
    "Natural gas, Europe": "27112100",
    "Liquefied natural gas, Japan": "271111",
    "Aluminum": "7601",
    "Sawnwood, Malaysian": "4407",
    "Gold": "7108",
    "Iron ore, cfr spot": "2601",
    "Coal, Australian": "2701",
    "Maize": "1005",
    "Chicken **": "207",
    "Tea, avg 3 auctions": "9012100",
    "Beef **": "201",
    "Logs, Malaysian": "4403",
    "Copper": "7403",
    "Wheat, US SRW": "1001",
    "Banana, Europe": "803",
    "Plywood": "4412",
    "Rubber, TSR20 **": "4001",
    "Coffee, Arabica": "9011100",
    "Platinum": "7110",
    "Shrimps, Mexican": "306",
    "Sugar, world": "1701",
    "Urea ": "310210",
    "Palm oil": "1511",
    "Soybeans": "1201",
    "Rapeseed oil": "1514",
    "Tobacco, US import u.v.": "2401",
    "Zinc": "7901",
    "Barley": "1003",
    "Nickel": "7502",
    "Rice, Thai 5% ": "1006",
    "Orange": "80510",
    "Lead": "7801",
    "Sunflower oil": "15121990",
    "Cocoa": "180100",
    "Soybean oil": "1507",
    "Silver": "7106",
    "Lamb **": "204",
    "Potassium chloride **": "310420",
    "Phosphate rock": "2510",
    "DAP": "310530",
    "Tin": "8001",
    "Groundnuts": "12024200",
    "Fish meal": "23012000",
    "Cotton, A Index": "5201",
    "Groundnut oil **": "9024000",
    "Coconut oil": "15131999",
    "Sorghum": "1007",
    "Crude oil, average": '2709',
    "Palm kernel oil": '151329',
    "Soybean meal": '230400'
}



percentage_increase['hs6'] = percentage_increase['product'].map(hs6_codes)
percentage_increase.dropna(inplace=True)  # Drop rows where 'hs6' is NaN

# create dict hs6: percentage_increase
hs6_percentage_increase = percentage_increase.set_index('hs6')['percentage_increase'].to_dict()
hs6_percentage_increase

{'15121990': 67.25081991598961,
 '2701': 59.45163747143947,
 '7502': 51.74937598969376,
 '27112100': 50.00693833891724,
 '1001': 37.365245101362795,
 '310530': 34.13737882124167,
 '2709': 33.93311089927312,
 '1507': 33.16094613353658,
 '1511': 32.136616125937884,
 '207': 29.414880294659305,
 '310420': 24.422438043353743,
 '1005': 21.294794068254934,
 '1201': 18.867737784962554,
 '7601': 16.38034850531274,
 '1514': 15.918643050135111,
 '2601': 14.743831585301434,
 '230400': 14.233888582879056,
 '151329': 11.189139216409586,
 '15131999': 10.618310236392299,
 '7901': 10.087687614263412,
 '7106': 9.30995768201053,
 '7108': 7.2581799759914505,
 '5201': 6.876183263915185,
 '803': 6.4336885630862595,
 '8001': 5.163632970183078,
 '7110': 4.93989840567319,
 '7403': 4.5853037207866345,
 '1701': 4.555433589462135,
 '201': 4.508780256288561,
 '2510': 3.2461156356495144,
 '310210': 3.086084264751058,
 '271111': 2.898216726155981,
 '2401': 1.7540505663623676,
 '306': 1.1780495079033733,
 '12024200': 0.7941603866040351,
 '7801': 0.5570684220683251,
 '204': 0.23244156549283415,
 '180100': -0.33841839050645545,
 '1006': -1.1709601873536302,
 '4001': -1.8942161767185568,
 '4407': -2.8394424367578828,
 '4403': -3.127370816824157,
 '4412': -3.1273708168258203,
 '80510': -3.3411137041536927,
 '9011100': -4.648074369189914,
 '9012100': -8.674423257147277,
 '9024000': -13.523944929072886}